---
- name: Include package tasks
  ansible.builtin.import_tasks: packages.yml


- name: Include service tasks
  ansible.builtin.import_tasks: service.yml


- name: Include users tasks
  ansible.builtin.import_tasks: users.yml

#- name: Include default network tasks (optional)
#  ansible.builtin.import_tasks: network.yml
#  when: kvm_libvirt_ensure_default_network

- name: Include firewall tasks (optional)
  ansible.builtin.import_tasks: firewall.yml
  when: kvm_libvirt_manage_firewall
