---
- name: Install required packages (Debian)
  apt:
    name:
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - virtinst
      - virt-manager
    state: present
    update_cache: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install required packages (RedHat)
  yum:
    name:
      - qemu-kvm
      - libvirt
      - libvirt-daemon-system
      - bridge-utils
      - virt-install
      - virt-manager
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Install extra KVM packages if any
  package:
    name: "{{ extra_kvm_packages }}"
    state: present
  when: extra_kvm_packages | length > 0

- name: Ensure libvirtd service is enabled and started
  service:
    name: libvirtd
    state: started
    enabled: yes

- name: Enable nested virtualization (Intel)
  copy:
    dest: /etc/modprobe.d/kvm-intel.conf
    content: "options kvm-intel nested=1\n"
  notify: Reload kvm module
  when:
    - enable_nested_virtualization
    - ansible_facts['processor'][0] is search("Intel")

- name: Enable nested virtualization (AMD)
  copy:
    dest: /etc/modprobe.d/kvm-amd.conf
    content: "options kvm-amd nested=1\n"
  notify: Reload kvm module
  when:
    - enable_nested_virtualization
    - ansible_facts['processor'][0] is search("AMD")

